test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.private", "install.nourl", "install.multi", "install.subdir", "change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.nextcloud_domain = "nextcloud.tld"
